Repository MindFlavor/AzureSDKForRust, pull requests merged in 2020-05, with the labels that each got.

#266 Add client encryption keys resource quota
  azure_sdk_cosmos/src/resource_quota.rs
Labels: CosmosDB, bugfix

#265 Dependency bump
  azure_sdk_auth_aad/Cargo.toml
  azure_sdk_core/Cargo.toml
  azure_sdk_cosmos/Cargo.toml
  azure_sdk_cosmos/src/lib.rs
  azure_sdk_service_bus/Cargo.toml
  azure_sdk_service_bus/examples/service_bus00.rs
  azure_sdk_service_bus/src/event_hub/client.rs
  azure_sdk_service_bus/src/event_hub/mod.rs
  azure_sdk_service_bus/src/lib.rs
  azure_sdk_service_bus/tests/event_hub.rs
  azure_sdk_storage_account/Cargo.toml
  azure_sdk_storage_blob/Cargo.toml
  azure_sdk_storage_core/Cargo.toml
  azure_sdk_storage_core/src/rest_client.rs
  azure_sdk_storage_table/Cargo.toml
Labels: Core, dependency

#274 CosmosDB - Support for triggers
  README.md
  azure_sdk_auth_aad/Cargo.toml
  azure_sdk_core/Cargo.toml
  azure_sdk_core/src/enumerations.rs
  azure_sdk_cosmos/Cargo.toml
  azure_sdk_cosmos/examples/trigger_00.rs
  azure_sdk_cosmos/src/clients/client.rs
  azure_sdk_cosmos/src/clients/collection_client.rs
  azure_sdk_cosmos/src/clients/mod.rs
  azure_sdk_cosmos/src/clients/trigger_client.rs
  azure_sdk_cosmos/src/consistency_level.rs
  azure_sdk_cosmos/src/lib.rs
  azure_sdk_cosmos/src/prelude.rs
  azure_sdk_cosmos/src/requests/create_or_replace_trigger_builder.json
  azure_sdk_cosmos/src/requests/create_or_replace_trigger_builder.rs
  azure_sdk_cosmos/src/requests/delete_trigger_builder.json
  azure_sdk_cosmos/src/requests/delete_trigger_builder.rs
  azure_sdk_cosmos/src/requests/list_triggers_builder.json
  azure_sdk_cosmos/src/requests/list_triggers_builder.rs
  azure_sdk_cosmos/src/requests/mod.rs
  azure_sdk_cosmos/src/responses/create_trigger_response.rs
  azure_sdk_cosmos/src/responses/delete_trigger_response.rs
  azure_sdk_cosmos/src/responses/list_triggers_response.rs
  azure_sdk_cosmos/src/responses/mod.rs
  azure_sdk_cosmos/src/trigger.rs
  azure_sdk_cosmos/tests/trigger.rs
  azure_sdk_service_bus/Cargo.toml
  azure_sdk_storage_account/Cargo.toml
  azure_sdk_storage_blob/Cargo.toml
  azure_sdk_storage_core/Cargo.toml
  azure_sdk_storage_table/Cargo.toml
Labels: CosmosDB, enhancement
